# ---- Backend Dockerfile ----
FROM python:3.11-slim

# Empêche Python de générer des fichiers .pyc et force l'affichage immédiat
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Répertoire de travail
WORKDIR /app

# Installation des dépendances système nécessaires à mysqlclient
RUN apt-get update && apt-get install -y \
    pkg-config \
    default-libmysqlclient-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copie des dépendances Python
COPY requirements.txt .

# Installation des dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copie du code Django
COPY . .

# Commande par défaut : attente + migration + lancement du serveur
CMD sh -c "echo '⏳ Waiting for MariaDB...' && sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
