from django.urls import path

from .views import (
    AdminAssignTeamView,
    AdminResetPasswordView,
    ChangePasswordView,
    ClockInView,
    ClockOutView,
    DeleteAccountView,
    LoginView,
    MeView,
    MyTeamView,
    MyTodayStatusView,
    RegisterView,
    TaskDetailView,
    TaskListCreateView,
    TeamDetailView,
    TeamListCreateView,
    TeamMembersView,
    TeamMemberTimeEntriesView,
    TeamStatusSetView,
    TeamTimeEntryUpsertView,
    TimeEntryListView,
    UpdateUserView,
    UserListCreateView,
    WorkingHoursView,
)

urlpatterns = [
    path("", UserListCreateView.as_view(), name="user-list"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("me/", MeView.as_view(), name="me"),
    path("update/", UpdateUserView.as_view(), name="update"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("admin/reset-password/", AdminResetPasswordView.as_view(), name="admin-reset-password"),
    path("delete/", DeleteAccountView.as_view(), name="delete-account"),
    path("clock-in/", ClockInView.as_view(), name="clock-in"),
    path("clock-out/", ClockOutView.as_view(), name="clock-out"),
    path("time-entries/", TimeEntryListView.as_view(), name="time-entries"),
    path("teams/", TeamListCreateView.as_view(), name="team-list-create"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("team/members/", TeamMembersView.as_view(), name="team-members"),
    path("team/assign/", AdminAssignTeamView.as_view(), name="admin-assign-team"),
    path("team/members/<int:user_id>/time-entries/", TeamMemberTimeEntriesView.as_view(), name="team-member-entries"),
    path("team/members/<int:user_id>/working-hours/", WorkingHoursView.as_view(), name="working-hours"),
    path("team/status/", TeamStatusSetView.as_view(), name="team-status-set"),
    path("team/time-entry/", TeamTimeEntryUpsertView.as_view(), name="team-time-entry-upsert"),
    path("me/status/", MyTodayStatusView.as_view(), name="my-today-status"),
    path("me/team/", MyTeamView.as_view(), name="my-team"),
    path("tasks/", TaskListCreateView.as_view(), name="task-list-create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
]
