from django.urls import path

from .views import (
    AdminAssignManagerView,
    ChangePasswordView,
    ClockInView,
    ClockOutView,
    DeleteAccountView,
    Enable2FAView,
    LoginView,
    MyTeamView,
    MyTodayStatusView,
    RegisterView,
    TaskDetailView,
    TaskListCreateView,
    TeamMembersView,
    TeamMemberTimeEntriesView,
    TeamStatusSetView,
    TeamTimeEntryUpsertView,
    TimeEntryListView,
    UpdateUserView,
    UserListCreateView,
    Verify2FAView,
)

urlpatterns = [
    path("", UserListCreateView.as_view(), name="user-list"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("update/", UpdateUserView.as_view(), name="update"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("delete/", DeleteAccountView.as_view(), name="delete-account"),
    path("enable-2fa/", Enable2FAView.as_view(), name="enable-2fa"),
    path("verify-2fa/", Verify2FAView.as_view(), name="verify-2fa"),
    path("clock-in/", ClockInView.as_view(), name="clock-in"),
    path("clock-out/", ClockOutView.as_view(), name="clock-out"),
    path("time-entries/", TimeEntryListView.as_view(), name="time-entries"),
    path("team/members/", TeamMembersView.as_view(), name="team-members"),
    path("team/assign-manager/", AdminAssignManagerView.as_view(), name="admin-assign-manager"),
    path("team/members/<int:user_id>/time-entries/", TeamMemberTimeEntriesView.as_view(), name="team-member-entries"),
    path("team/status/", TeamStatusSetView.as_view(), name="team-status-set"),
    path("team/time-entry/", TeamTimeEntryUpsertView.as_view(), name="team-time-entry-upsert"),
    path("me/status/", MyTodayStatusView.as_view(), name="my-today-status"),
    path("me/team/", MyTeamView.as_view(), name="my-team"),
    path("tasks/", TaskListCreateView.as_view(), name="task-list-create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),

]
