# Generated by Django 6.0 on 2025-12-12 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_timeentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-clock_in', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='clock_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='updated_at',
        ),
    ]
