# Generated by Django 5.2.10 on 2026-01-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Deadline date and time', null=True),
        ),
    ]
